### ISSUE TITLE
Javascript Capstone Project Setup

### ISSUE THREAD

**Issue by yigitm** [iwillteixeira/javascript-capstone#1]
Project Link: [https://github.com/iwillteixeira/javascript-capstone/projects/2](https://github.com/iwillteixeira/javascript-capstone/projects/2)

Project Team Members:
- Willian Teixeira - Student A
- George Magdy - Student B
- Yiğit Mersin - Student C

**Comment by elyor-doniyorov** [comment]
Hi Team, 👋

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
![Screenshot (74)_LI](https://user-images.githubusercontent.com/67087664/146806805-365f62b2-cc7d-423a-9d4e-c38865d48b76.jpg)
 - [ ] Make sure you have 20 cards from the given template are added and assigned to team members. This [template ](https://github.com/microverseinc/curriculum-javascript/projects/1)should be copied.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omar-labana** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
